### ISSUE TITLE
unable to create symlink lni-instructions.pdf: File name too long

### ISSUE THREAD

**Issue by KLJ42** [gi-ev/LNI#73] opened 2018-12-05 10:06 UTC
Hi,
first of all thanks for this repo, because I think it is very nice to have!

Nevertheless I am unable to clone the repo as the error 

`unable to create symlink lni-instructions.pdf: File name too long`

occurs by using the terminal (macOS 10.13).

Thanks in advance

**Comment by sieversMartin** [comment] 2018-12-05 10:14
Hi,

this is not an issue regarding the repository itself, but your Git installation. Please try to clone to another not so deep directory and read https://stackoverflow.com/questions/22575662/filename-too-long-in-git-for-windows

**Comment by christgau** [comment] 2019-01-30 07:38
This might be unrelated, but I stumbled across a similar problem yesterday on a Debian Stable installation and I can reproduce on an up-to-date Arch machine:
```
$ cd /tmp
$ git --version
git version 2.20.1
$ git clone https://github.com/gi-ev/LNI.git
Cloning into 'LNI'...
remote: Enumerating objects: 639, done.
remote: Total 639 (delta 0), reused 0 (delta 0), pack-reused 639
Receiving objects: 100% (639/639), 3.08 MiB | 5.06 MiB/s, done.
Resolving deltas: 100% (454/454), done.
$ ls -l LNI
total 580K
-rw-r--r-- 1 christgau users 3.2K Jan 30 08:26 CHANGELOG.md
-rw-r--r-- 1 christgau users  894 Jan 30 08:26 CONTRIBUTING.md
-rw-r--r-- 1 christgau users 1.8K Jan 30 08:26 lni-author-template.tex
-rw-r--r-- 1 christgau users  24K Jan 30 08:26 lni.bst
-rw-r--r-- 1 christgau users  20K Jan 30 08:26 lni.cls
-rw-r--r-- 1 christgau users  85K Jan 30 08:26 lni.dtx
-rw-r--r-- 1 christgau users  24K Jan 30 08:26 lnig.bst
-rw-r--r-- 1 christgau users 4.2K Jan 30 08:26 lni.ins
lrwxrwxrwx 1 christgau users 1.9K Jan 30 08:26 lni-instructions.pdf -> '%PDF-1.5'$'\n''%'$'\320\324\305\330\n''1 0 obj'$'
...
```
Seems as if the git tries to create the PDF instructions as a symlink and the link's target appears to be the content of the PDF or at least the first (roundabout) 2k of it. 

The suggested link to stackoverflow is applicable, because a) I'm running linux and b) even if the longpath option is set the same problem still occurs.

**Comment by sieversMartin** [comment] 2019-01-30 08:19
Thank you. I got the same on my Ubuntu system when trying again. I recreated the symlink (124e9becb643689f530689bb64ee20c70369c70d) and hope, that it "survives" ...

**Comment by koppor** [comment] 2019-02-17 11:50
Works great in my WSL setup, too. Thus, I close the issue. Please reopen if the issue persists.

**Closed by koppor** 2019-02-17 11:50 UTC
